/*
 * Arch 2024 fall course code.
 * - This is an example C code of hello world.
 * - This code is generated by Github Copilot.
 * - The program will print "Hello, World!" to the console.
 * - This program is used for testing the functionality of gem5.
 */

#include <stdio.h>

int main() {
    printf("Hello, World!\n");
    return 0;
}
