/*
 * Arch 2024 fall course code.
 * - This is an example C code of Shell Sort algorithm.
 * - This code is generated by Github Copilot.
 * - This code defines the data structures for Shell Sort algorithm.
 * - This program is used for benchmarking the Branch Predictor and Cache
 * Prefetcher in gem5.
 */

typedef struct Person {
    int id;
    int age;
    int height;
    int weight;
    double score;
} Person;
