/*
 * Arch 2024 fall course code.
 * - This is a C++ code generating arrays for Shell Sort algorithm.
 * - This code is generated by Github Copilot.
 * - This program will generate an array of person with random age, 
 * height, weight and score.
 */

#include "shell_sort.h"
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iostream>
#include <random>

int main(int argc, char *argv[]) {
    if (argc != 3) {
        std::cerr << "Usage: " << argv[0] << "<file name> <number of persons>"
                  << std::endl;
        return 1;
    }

    std::ofstream file(argv[1]);
    if (!file.is_open()) {
        std::cerr << "Error: cannot open file " << argv[1] << std::endl;
        return 1;
    }

    int n = std::atoi(argv[2]);
    std::random_device rd;
    std::mt19937 gen(rd());
    int id = 0;
    std::uniform_int_distribution<int> age_dist(1, 100);
    std::uniform_int_distribution<int> height_dist(100, 200);
    std::uniform_int_distribution<int> weight_dist(40, 100);
    std::uniform_real_distribution<double> score_dist(0.0, 100000.0);
    std::uniform_int_distribution<int> name_dist(0, 25);

    file << "#include \"shell_sort.h\"" << std::endl;
    file << "#define N " << n << std::endl;
    file << "Person PERSONS[" << n << "] = {" << std::endl;
    for (int i = 0; i < n; i++) {
        file << "  {";
	file << id++ << ", ";
        file << age_dist(gen) << ", ";
        file << height_dist(gen) << ", ";
        file << weight_dist(gen) << ", ";
        file << score_dist(gen) << ", ";
        file << "}";
        if (i < n - 1) file << ",";
        file << std::endl;
    }
    file << "};" << std::endl;
    file.close();

    return 0;
}
