/*
 * Arch 2024 fall course code.
 * - This is an example C code of Shell Sort algorithm.
 * - This code is generated by Github Copilot.
 * - The array is directly included to avoid the reading process for a
 * quicker simulation.
 * - This program will sort the persons based on their scores using
 * Shell Sort algorithm.
 * - This program is used for benchmarking the Branch Predictor and Cache
 * Prefetcher in gem5.
 */

#include "shell_sort.in"

void shell_sort(Person arr[], int n) {
    int gap = n / 2;
    while (gap > 0) {
        for (int i = gap; i < n; i++) {
            Person temp = arr[i];
            int j = i;
            while (j >= gap && arr[j - gap].score > temp.score) {
                arr[j] = arr[j - gap];
                j -= gap;
            }
            arr[j] = temp;
        }
        gap /= 2;
    }
}

int main() {
    shell_sort(PERSONS, N);
    return 0;
}
