/*
 * Arch 2024 fall course code.
 * - This is an example C code of SPFA algorithm.
 * - This code is generated by Github Copilot.
 * - The graph is directly included to avoid the reading process
 * for a quicker simulation.
 * - This program will find the shortest path from the source node to all
 * other nodes in the graph using SPFA algorithm.
 * - This program is used for benchmarking the Branch Predictor and Cache
 * Prefetcher in gem5.
 */

#include "spfa.in"

void spfa(int n, int s, Graph *g, int dis[], int vis[], RingQueue *q) {
    dis[s] = 0;
    vis[s] = 0;
    push(q, s);
    while (empty(q) == 0) {
        int u = front(q);
        pop(q);
        vis[u] = 1;
        for (int i = g->head[u]; i != -1; i = g->edge[i].next) {
            int v = g->edge[i].to;
            if (dis[u] + g->edge[i].w < dis[v]) {
                dis[v] = dis[u] + g->edge[i].w;
                if (vis[v]) {
                    push(q, v);
                    vis[v] = 0;
                }
            }
        }
    }
}

int main() {
    spfa(N, S, &G, DIS, VIS, &Q);
    return 0;
}
