/*
 * Arch 2024 fall course code.
 * - This is an example C code of SPFA algorithm.
 * - This code is generated by Github Copilot.
 * - This code defines the data structures and functions for SPFA algorithm.
 * - This program is used for benchmarking the Branch Predictor and Cache
 * Prefetcher in gem5.
 */

#define MAXN 2000000
#define MAXM 20000000

typedef struct Edge {
    int to;
    int w;
    int next;
} Edge;

typedef int EdgeIndex;

typedef struct Graph {
    int head[MAXN];
    Edge edge[MAXM];
} Graph;

typedef struct RingQueue {
    int data[MAXN];
    int head;
    int tail;
} RingQueue;

void push(RingQueue *q, int x) {
    q->data[q->tail++] = x;
    q->tail %= MAXN;
}

void pop(RingQueue *q) {
    q->head++;
    q->head %= MAXN;
}

int front(RingQueue *q) { return q->data[q->head]; }

int empty(RingQueue *q) { return q->head == q->tail; }
